"""outbox_event

Revision ID: ab8365cc15b1
Revises: dab1b0c153e8
Create Date: 2026-07-26 00:35:57.771116

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab8365cc15b1'
down_revision: str | None = 'dab1b0c153e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.add_column('outbox_events', sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('outbox_events', sa.Column('aggregate_id', sa.Uuid(), nullable=False))
    op.add_column('outbox_events', sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('outbox_events', sa.Column('event_version', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('outbox_events', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_events', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['occurred_at'], unique=False, schema='public', postgresql_where=sa.text('published_at IS NULL'))
    op.create_index(op.f('ix_public_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False, schema='public')
    op.drop_column('outbox_events', 'topic')
    op.drop_constraint(op.f('tenant_migrations_tenant_id_fkey'), 'tenant_migrations', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_migrations', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tenant_plugins_plugin_id_fkey'), 'tenant_plugins', type_='foreignkey')
    op.drop_constraint(op.f('tenant_plugins_tenant_id_fkey'), 'tenant_plugins', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_plugins', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'tenant_plugins', 'plugins', ['plugin_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tenant_provisioning_jobs_tenant_id_fkey'), 'tenant_provisioning_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_provisioning_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_provisioning_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_provisioning_jobs_tenant_id_fkey'), 'tenant_provisioning_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_plugins', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tenant_plugins', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_plugins_tenant_id_fkey'), 'tenant_plugins', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('tenant_plugins_plugin_id_fkey'), 'tenant_plugins', 'plugins', ['plugin_id'], ['id'])
    op.drop_constraint(None, 'tenant_migrations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_migrations_tenant_id_fkey'), 'tenant_migrations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('outbox_events', sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_public_outbox_events_tenant_id'), table_name='outbox_events', schema='public')
    op.drop_index(op.f('ix_public_outbox_events_aggregate_id'), table_name='outbox_events', schema='public')
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events', schema='public', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'attempts')
    op.drop_column('outbox_events', 'published_at')
    op.drop_column('outbox_events', 'occurred_at')
    op.drop_column('outbox_events', 'event_version')
    op.drop_column('outbox_events', 'event_type')
    op.drop_column('outbox_events', 'aggregate_id')
    op.drop_column('outbox_events', 'aggregate_type')
    op.drop_column('outbox_events', 'tenant_id')
    # ### end Alembic commands ###
