"""init_public

Revision ID: dab1b0c153e8
Revises: 
Create Date: 2026-07-26 00:23:10.811778

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dab1b0c153e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_reputation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_national_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_index(op.f('ix_public_global_reputation_contact_national_id'), 'global_reputation', ['contact_national_id'], unique=False, schema='public')
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_table('platform_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_table('plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_index(op.f('ix_public_plugins_name'), 'plugins', ['name'], unique=False, schema='public')
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('shard_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('db_cluster_ref', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('provisioning_state', sa.Enum('CREATED', 'SCHEMA_CREATED', 'TABLES_CREATED', 'COA_SEEDED', 'BRANCH_CREATED', 'TREASURY_CREATED', 'WAREHOUSE_CREATED', 'SEQUENCES_CREATED', 'PERIODS_CREATED', 'COMPLETE', 'FAILED', name='provisioningstate'), nullable=False),
    sa.Column('trust_consent', sa.Boolean(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING_SETUP', 'SUSPENDED', name='tenantstatus'), nullable=False),
    sa.Column('active_plugins', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_name', name='uq_tenants_schema_name'),
    sa.UniqueConstraint('slug', name='uq_tenants_slug'),
    schema='public',
    )
    op.create_index(op.f('ix_public_tenants_name'), 'tenants', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenants_slug'), 'tenants', ['slug'], unique=False, schema='public')
    op.create_table('tenant_migrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('target_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'] ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_index(op.f('ix_public_tenant_migrations_tenant_id'), 'tenant_migrations', ['tenant_id'], unique=False, schema='public')
    op.create_table('tenant_plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['public.plugins.id'] ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'] ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_index(op.f('ix_public_tenant_plugins_plugin_id'), 'tenant_plugins', ['plugin_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_plugins_tenant_id'), 'tenant_plugins', ['tenant_id'], unique=False, schema='public')
    op.create_table('tenant_provisioning_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'] ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    )
    op.create_index(op.f('ix_public_tenant_provisioning_jobs_tenant_id'), 'tenant_provisioning_jobs', ['tenant_id'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'STAFF', 'SALES', 'ACCOUNTING', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'] ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    schema='public',
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_tenant_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_tenant_provisioning_jobs_tenant_id'), table_name='tenant_provisioning_jobs', schema='public')
    op.drop_table('tenant_provisioning_jobs', schema='public')
    op.drop_index(op.f('ix_public_tenant_plugins_tenant_id'), table_name='tenant_plugins', schema='public')
    op.drop_index(op.f('ix_public_tenant_plugins_plugin_id'), table_name='tenant_plugins', schema='public')
    op.drop_table('tenant_plugins', schema='public')
    op.drop_index(op.f('ix_public_tenant_migrations_tenant_id'), table_name='tenant_migrations', schema='public')
    op.drop_table('tenant_migrations', schema='public')
    op.drop_index(op.f('ix_public_tenants_slug'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_name'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_plugins_name'), table_name='plugins', schema='public')
    op.drop_table('plugins', schema='public')
    op.drop_table('platform_audit_logs', schema='public')
    op.drop_table('outbox_events', schema='public')
    op.drop_index(op.f('ix_public_global_reputation_contact_national_id'), table_name='global_reputation', schema='public')
    op.drop_table('global_reputation', schema='public')
    # ### end Alembic commands ###
