"""
alembic/tenant/env.py — Alembic Environment for Tenant Schemas

This script handles migrations for a specific tenant schema, passed via -x schema=<name>.

Schema translation strategy:
  Alembic 1.18.x does not support context.configure(schema_translate_map=...).
  SQLAlchemy 2.0's execution_options(schema_translate_map=...) is for DML only
  and is NOT applied to raw DDL generated by Alembic ops (op.add_column, etc.).

  Instead, we attach a `before_cursor_execute` event on the sync engine that
  replaces the literal token `"tenant".` with `"<real_schema_name>".` in every
  SQL statement just before it is sent to asyncpg.  This is deterministic and
  works for all DDL ops regardless of Alembic/SQLAlchemy internals.
"""
from __future__ import annotations

import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import event, pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import app.core.audit.models
import app.core.observability.models
import app.core.sequences.models
import app.modules.accounting.models
import app.modules.contacts.models

# Import models to ensure they are registered with TenantBase.metadata
import app.modules.core.models
import app.modules.inventory.models  # noqa: F401
import app.modules.sales.models  # noqa: F401
import app.plugins.inventory.models  # noqa: F401
import app.modules.eta.models  # noqa: F401
from app.core.config import settings
from app.core.db.base import TenantBase

target_metadata = TenantBase.metadata

config = context.config
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def _install_schema_translate(sync_engine, schema_name: str) -> None:
    """
    Install a before_cursor_execute event listener that rewrites every SQL
    statement sent to asyncpg, replacing the logical schema token 'tenant'
    with the real tenant schema name.

    Handles both forms that Alembic/SQLAlchemy DDL may emit:
      - Unquoted:  tenant.tablename  → "schema_name".tablename
      - Quoted:   "tenant".tablename → "schema_name".tablename
    """
    import re
    # Match 'tenant.' or '"tenant".' but NOT 'tenant_something' (word-boundary safe)
    _pattern = re.compile(r'"tenant"\.|(?<!["\w])tenant\.')
    _replacement = f'"{schema_name}".'

    @event.listens_for(sync_engine, "before_cursor_execute", retval=True)
    def _rewrite_schema(conn, cursor, statement, parameters, context, executemany):
        if "tenant" in statement:
            statement = _pattern.sub(_replacement, statement)
        return statement, parameters


def do_run_migrations(connection, schema_name: str) -> None:
    """Execute Alembic migrations for a single tenant schema."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        version_table="alembic_version",
        version_table_schema=schema_name,
        include_schemas=False,  # DO NOT include public or other schemas
        compare_type=True,
        compare_server_default=True,
        # Only include tables inside this exact schema and ignore alembic_version
        include_object=lambda obj, name, type_, reflected, compare_to: (
            False if name == "alembic_version" else (
                obj.schema == "tenant" if type_ == "table" else True
            )
        ),
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    # Read target schema from `-x schema=tenant_xxx`
    x_args = context.get_x_argument(as_dictionary=True)
    schema_name = x_args.get("schema")

    if not schema_name:
        raise ValueError("Tenant migrations require a schema argument: -x schema=<name>")

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    # Install the schema-rewriting listener on the *sync* engine that
    # asyncpg actually uses under the hood.
    _install_schema_translate(connectable.sync_engine, schema_name)

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations, schema_name)

    await connectable.dispose()


def run_migrations_offline() -> None:
    x_args = context.get_x_argument(as_dictionary=True)
    schema_name = x_args.get("schema")

    if not schema_name:
        raise ValueError("Tenant migrations require a schema argument: -x schema=<name>")

    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table_schema=schema_name,
        include_schemas=False,
    )

    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_async_migrations())
