"""init_tenant

Revision ID: 226439fee167
Revises: 
Create Date: 2026-07-26 00:23:22.451488+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '226439fee167'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant',
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype', schema='tenant'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tenant.accounts.id'] ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_accounts_code'),
    schema='tenant',
    )
    op.create_index('ix_accounts_type', 'accounts', ['account_type'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_accounts_code'), 'accounts', ['code'], unique=False, schema='tenant')
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_type', sa.Enum('CUSTOMER', 'SUPPLIER', name='contacttype', schema='tenant'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'ARCHIVED', name='contactstatus', schema='tenant'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('phone_alt', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('cod_risk_score', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.000'), nullable=False),
    sa.Column('cod_rejection_count', sa.Integer(), nullable=False),
    sa.Column('cod_acceptance_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('cod_risk_score >= 0.000 AND cod_risk_score <= 1.000', name='ck_contacts_risk_score_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant',
    )
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False, schema='tenant')
    op.create_index('ix_contacts_type', 'contacts', ['contact_type'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_contacts_branch_id'), 'contacts', ['branch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_contacts_name'), 'contacts', ['name'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_contacts_phone'), 'contacts', ['phone'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_contacts_phone_e164'), 'contacts', ['phone_e164'], unique=False, schema='tenant')
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0 AND quantity_on_hand >= 0', name='ck_items_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_items_sku'),
    schema='tenant',
    )
    op.create_index(op.f('ix_tenant_items_name'), 'items', ['name'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_items_sku'), 'items', ['sku'], unique=False, schema='tenant')
    op.create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='journalentrystatus', schema='tenant'), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('entry_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant',
    )
    op.create_index('ix_journal_entries_created_at', 'journal_entries', ['created_at'], unique=False, schema='tenant')
    op.create_index('ix_journal_entries_status', 'journal_entries', ['status'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_journal_entries_branch_id'), 'journal_entries', ['branch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_journal_entries_reference'), 'journal_entries', ['reference'], unique=False, schema='tenant')
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PAID', 'CANCELLED', name='invoicestatus', schema='tenant'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['tenant.contacts.id'] ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_invoices_number'),
    schema='tenant',
    )
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_invoices_contact_id'), 'invoices', ['contact_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False, schema='tenant')
    op.create_table('transaction_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('cost_center_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('(debit >= 0 AND credit >= 0) AND NOT (debit > 0 AND credit > 0) AND (debit > 0 OR credit > 0)', name='ck_transaction_lines_debit_xor_credit'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['tenant.journal_entries.id'] ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant',
    )
    op.create_index(op.f('ix_tenant_transaction_lines_account_code'), 'transaction_lines', ['account_code'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_transaction_lines_branch_id'), 'transaction_lines', ['branch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_transaction_lines_contact_id'), 'transaction_lines', ['contact_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_transaction_lines_cost_center_id'), 'transaction_lines', ['cost_center_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_transaction_lines_journal_entry_id'), 'transaction_lines', ['journal_entry_id'], unique=False, schema='tenant')
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_lines_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_lines_price'),
    sa.ForeignKeyConstraint(['invoice_id'], ['tenant.invoices.id'] ),
    sa.ForeignKeyConstraint(['item_id'], ['tenant.items.id'] ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant',
    )
    op.create_index(op.f('ix_tenant_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_invoice_lines_item_id'), 'invoice_lines', ['item_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_invoice_lines_item_id'), table_name='invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoice_lines_invoice_id'), table_name='invoice_lines', schema='tenant')
    op.drop_table('invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_transaction_lines_journal_entry_id'), table_name='transaction_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_transaction_lines_cost_center_id'), table_name='transaction_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_transaction_lines_contact_id'), table_name='transaction_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_transaction_lines_branch_id'), table_name='transaction_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_transaction_lines_account_code'), table_name='transaction_lines', schema='tenant')
    op.drop_table('transaction_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoices_invoice_number'), table_name='invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoices_contact_id'), table_name='invoices', schema='tenant')
    op.drop_index('ix_invoices_status', table_name='invoices', schema='tenant')
    op.drop_table('invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_reference'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_branch_id'), table_name='journal_entries', schema='tenant')
    op.drop_index('ix_journal_entries_status', table_name='journal_entries', schema='tenant')
    op.drop_index('ix_journal_entries_created_at', table_name='journal_entries', schema='tenant')
    op.drop_table('journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_items_sku'), table_name='items', schema='tenant')
    op.drop_index(op.f('ix_tenant_items_name'), table_name='items', schema='tenant')
    op.drop_table('items', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_phone_e164'), table_name='contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_phone'), table_name='contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_name'), table_name='contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_branch_id'), table_name='contacts', schema='tenant')
    op.drop_index('ix_contacts_type', table_name='contacts', schema='tenant')
    op.drop_index('ix_contacts_status', table_name='contacts', schema='tenant')
    op.drop_table('contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_accounts_code'), table_name='accounts', schema='tenant')
    op.drop_index('ix_accounts_type', table_name='accounts', schema='tenant')
    op.drop_table('accounts', schema='tenant')
    op.drop_table('accounting_periods', schema='tenant')
    # ### end Alembic commands ###
