"""add_missing_tenant_tables

Revision ID: 5bec5c78a41f
Revises: k1f6g7h8i9j0
Create Date: 2026-08-09 17:35:30.458127+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bec5c78a41f'
down_revision: Union[str, None] = 'k1f6g7h8i9j0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_invoice_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurringfrequency', schema='tenant'), nullable=False),
    sa.Column('next_issue_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='recurringstatus', schema='tenant'), nullable=False),
    sa.Column('invoice_template_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_recurring_invoice_profiles_customer_id'), 'recurring_invoice_profiles', ['customer_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_recurring_invoice_profiles_customer_id'), table_name='recurring_invoice_profiles', schema='tenant')
    op.drop_table('recurring_invoice_profiles', schema='tenant')
    # ### end Alembic commands ###
