"""create_missing_tables_and_columns

Revision ID: ddecea2865fa
Revises: d3e4f5a6b7c8
Create Date: 2026-08-09 19:48:34.965949+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ddecea2865fa'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # --- DEFENSIVE MIGRATION WRAPPERS ---
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    from alembic import context as alembic_context
    from alembic import op as alembic_op
    current_schema = alembic_context.get_context().version_table_schema

    # Cache tables, columns, and indexes to avoid N+1 queries to the DB
    _existing_tables = set()
    _existing_columns = set()
    _existing_indexes = set()

    _res_tables = bind.execute(sa.text("SELECT table_name FROM information_schema.tables WHERE table_schema = :s"), {"s": current_schema})
    for row in _res_tables:
        _existing_tables.add(row[0])

    _res_cols = bind.execute(sa.text("SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = :s"), {"s": current_schema})
    for row in _res_cols:
        _existing_columns.add((row[0], row[1]))

    _res_idx = bind.execute(sa.text("SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = :s AND c.relkind = 'i'"), {"s": current_schema})
    for row in _res_idx:
        _existing_indexes.add(row[0])

    def _table_exists(table_name: str) -> bool:
        return table_name in _existing_tables

    def _index_exists(index_name: str) -> bool:
        return index_name in _existing_indexes
        
    def _column_exists(table_name: str, column_name: str) -> bool:
        return (table_name, column_name) in _existing_columns

    def _safe_create_table(name, *args, **kwargs):
        if not _table_exists(name):
            alembic_op.create_table(name, *args, **kwargs)
            _existing_tables.add(name)

    def _safe_create_index(name, table_name, *args, **kwargs):
        if not _index_exists(name) and _table_exists(table_name):
            alembic_op.create_index(name, table_name, *args, **kwargs)
            _existing_indexes.add(name)

    def _safe_add_column(table_name, column, *args, **kwargs):
        # Unlike every _safe_create_table/_safe_create_index call site in
        # this file, none of the three _safe_add_column call sites passed
        # schema='tenant' — so alembic_op.add_column() emitted a bare
        # `ALTER TABLE document_sequences ADD COLUMN ...` with no schema
        # qualifier at all (not even the literal 'tenant.' token the env.py
        # schema-rewriter looks for), which resolved against the
        # connection's default search_path instead of the tenant schema and
        # failed with "relation does not exist" — the table only exists
        # under the real tenant_xxx schema. Default it here so every call
        # site is correct regardless of whether the caller remembers to
        # pass it explicitly.
        kwargs.setdefault("schema", "tenant")
        if _table_exists(table_name) and not _column_exists(table_name, column.name):
            alembic_op.add_column(table_name, column, *args, **kwargs)
            _existing_columns.add((table_name, column.name))
    # ------------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    _safe_create_table('accounting_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype', schema='tenant'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tenant.accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_accounts_code'),
    schema='tenant'
    )
    _safe_create_index('ix_accounts_type', 'accounts', ['account_type'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_accounts_code'), 'accounts', ['code'], unique=False, schema='tenant')
    _safe_create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('UI', 'API', 'AI_ASSISTED', 'SYSTEM_EVENT', 'IMPORT', name='auditsource', schema='tenant'), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index('ix_audit_logs_actor', 'audit_logs', ['actor_id'], unique=False, schema='tenant')
    _safe_create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False, schema='tenant')
    _safe_create_index('ix_audit_logs_occurred_at', 'audit_logs', ['created_at'], unique=False, schema='tenant')
    _safe_create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('batch_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'QUARANTINED', 'RECALLED', name='batchstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'batch_no', name='uq_batches_item_batch'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_batches_batch_no'), 'batches', ['batch_no'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_batches_item_id'), 'batches', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_batches_variant_id'), 'batches', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_branches_code'), 'branches', ['code'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_branches_name'), 'branches', ['name'], unique=False, schema='tenant')
    _safe_create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_type', sa.Enum('CUSTOMER', 'SUPPLIER', name='contacttype', schema='tenant'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'ARCHIVED', name='contactstatus', schema='tenant'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('phone_alt', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('cod_risk_score', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.000'), nullable=False),
    sa.Column('cod_rejection_count', sa.Integer(), nullable=False),
    sa.Column('cod_acceptance_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('cod_risk_score >= 0.000 AND cod_risk_score <= 1.000', name='ck_contacts_risk_score_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index('ix_contacts_status', 'contacts', ['status'], unique=False, schema='tenant')
    _safe_create_index('ix_contacts_type', 'contacts', ['contact_type'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_contacts_branch_id'), 'contacts', ['branch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_contacts_name'), 'contacts', ['name'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_contacts_phone'), 'contacts', ['phone'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_contacts_phone_e164'), 'contacts', ['phone_e164'], unique=False, schema='tenant')
    _safe_create_table('cost_consumptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('layer_id', sa.Uuid(), nullable=False),
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('qty_consumed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_at_consumption', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjustment_of_id', sa.Uuid(), nullable=True),
    sa.Column('adjustment_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_cost_consumptions_adjustment_of_id'), 'cost_consumptions', ['adjustment_of_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_cost_consumptions_layer_id'), 'cost_consumptions', ['layer_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_cost_consumptions_movement_id'), 'cost_consumptions', ['movement_id'], unique=False, schema='tenant')
    _safe_create_table('cost_layers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_original', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_current', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('landed_cost_applied', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty_received >= 0', name='ck_cost_layers_received'),
    sa.CheckConstraint('qty_remaining >= 0', name='ck_cost_layers_remaining'),
    sa.CheckConstraint('serial_id IS NULL OR qty_received = 1', name='ck_cost_layers_serial_layer_qty_is_one'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_cost_layers_batch_id'), 'cost_layers', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_cost_layers_item_id'), 'cost_layers', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_cost_layers_serial_id'), 'cost_layers', ['serial_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_cost_layers_variant_id'), 'cost_layers', ['variant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_cost_layers_warehouse_id'), 'cost_layers', ['warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('document_sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type', 'branch_id', 'fiscal_year', name='uq_doc_seq_type_branch_year'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_document_sequences_branch_id'), 'document_sequences', ['branch_id'], unique=False, schema='tenant')
    # BUGFIX: document_sequences was created back in f3a8c91d4e72, long before
    # this migration — so the _safe_create_table call above always no-ops for
    # it (table already exists) and the new 'document_type' column bundled
    # into that create_table call above NEVER actually gets added. Must be
    # backfilled explicitly via ALTER TABLE (add_column), not create_table.
    #
    # ORDERING BUG (fixed): the index on 'document_type' was originally
    # created here, BEFORE this add_column ran. On a schema where
    # document_sequences pre-existed without 'document_type' (i.e. every
    # tenant, since it was never added until this migration), that index
    # creation hit "column document_type does not exist" and aborted the
    # whole migration — 500ing every dashboard endpoint for that tenant
    # (they all depend on later tables that never got created because this
    # revision never committed). The index must be created AFTER the column
    # is guaranteed to exist, not before.
    _safe_add_column(
        'document_sequences',
        sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default=''),
    )
    _safe_create_index(op.f('ix_tenant_document_sequences_document_type'), 'document_sequences', ['document_type'], unique=False, schema='tenant')
    _safe_create_table('egs_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('code_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('code_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parent_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'variant_id', 'code_type', name='uq_egs_codes_item_variant_type'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_egs_codes_code_type'), 'egs_codes', ['code_type'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_egs_codes_code_value'), 'egs_codes', ['code_value'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_egs_codes_is_active'), 'egs_codes', ['is_active'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_egs_codes_item_id'), 'egs_codes', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_egs_codes_tenant_id'), 'egs_codes', ['tenant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_egs_codes_variant_id'), 'egs_codes', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('eta_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('internal_doc_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('internal_doc_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('eta_document_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('eta_document_type_version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('long_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('submission_uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('canonical_string_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('signature_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('translated_errors', sa.JSON(), nullable=True),
    sa.Column('date_time_issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('qr_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    # BUGFIX: eta_documents already exists by the time this migration runs
    # (created earlier in the chain by d3e4f5a6b7c8), so the _safe_create_table
    # call above always no-ops for it and 'eta_document_type' /
    # 'eta_document_type_version' bundled into that call above NEVER
    # actually get added. Backfill explicitly.
    _safe_add_column(
        'eta_documents',
        sa.Column('eta_document_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False, server_default=''),
    )
    _safe_add_column(
        'eta_documents',
        sa.Column('eta_document_type_version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default=''),
    )
    _safe_create_index(op.f('ix_tenant_eta_documents_eta_document_type'), 'eta_documents', ['eta_document_type'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_documents_internal_doc_id'), 'eta_documents', ['internal_doc_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_documents_internal_doc_type'), 'eta_documents', ['internal_doc_type'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_documents_state'), 'eta_documents', ['state'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_documents_submission_uuid'), 'eta_documents', ['submission_uuid'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_documents_tenant_id'), 'eta_documents', ['tenant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_documents_uuid'), 'eta_documents', ['uuid'], unique=False, schema='tenant')
    _safe_create_table('eta_receipt_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('pos_terminal_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('receipt_ids', sa.JSON(), nullable=False),
    sa.Column('receipt_count', sa.Integer(), nullable=False),
    sa.Column('batch_canonical_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('signature_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submission_uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_eta_receipt_batches_pos_terminal_id'), 'eta_receipt_batches', ['pos_terminal_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipt_batches_state'), 'eta_receipt_batches', ['state'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipt_batches_submission_uuid'), 'eta_receipt_batches', ['submission_uuid'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipt_batches_tenant_id'), 'eta_receipt_batches', ['tenant_id'], unique=False, schema='tenant')
    _safe_create_table('eta_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('internal_doc_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('previous_uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('date_time_issued', sa.DateTime(timezone=True), nullable=False),
    sa.Column('late_on_arrival', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('qr_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_eta_receipts_batch_id'), 'eta_receipts', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipts_internal_doc_id'), 'eta_receipts', ['internal_doc_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipts_receipt_number'), 'eta_receipts', ['receipt_number'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipts_state'), 'eta_receipts', ['state'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipts_tenant_id'), 'eta_receipts', ['tenant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_receipts_uuid'), 'eta_receipts', ['uuid'], unique=False, schema='tenant')
    _safe_create_table('eta_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('submission_uuid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_eta_submissions_submission_uuid'), 'eta_submissions', ['submission_uuid'], unique=True, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_submissions_tenant_id'), 'eta_submissions', ['tenant_id'], unique=False, schema='tenant')
    _safe_create_table('eta_tenant_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('client_secret_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('taxpayer_rin', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activity_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('branch_eta_codes', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('signing_provider', sa.String(length=30), nullable=False),
    sa.Column('preflight_state', sa.String(length=30), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('went_live_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_eta_tenant_configs_taxpayer_rin'), 'eta_tenant_configs', ['taxpayer_rin'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_eta_tenant_configs_tenant_id'), 'eta_tenant_configs', ['tenant_id'], unique=True, schema='tenant')
    _safe_create_table('item_barcodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name='uq_item_barcodes_barcode'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_item_barcodes_barcode'), 'item_barcodes', ['barcode'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_item_barcodes_item_id'), 'item_barcodes', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_item_barcodes_uom_id'), 'item_barcodes', ['uom_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_item_barcodes_variant_id'), 'item_barcodes', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('item_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('requires_batch', sa.Boolean(), nullable=False),
    sa.Column('requires_serial', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_item_variants_sku'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_item_variants_item_id'), 'item_variants', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_item_variants_sku'), 'item_variants', ['sku'], unique=False, schema='tenant')
    _safe_create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('egs_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('costing_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('requires_batch', sa.Boolean(), nullable=False),
    sa.Column('requires_serial', sa.Boolean(), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0 AND quantity_on_hand >= 0', name='ck_items_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_items_sku'),
    sa.UniqueConstraint('sku', name='uq_items_sku'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_items_egs_code'), 'items', ['egs_code'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_items_sku'), 'items', ['sku'], unique=False, schema='tenant')
    _safe_create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED', 'WITHDRAWN', 'REVERSED', 'CLOSED', name='documentstate', schema='tenant'), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_of_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOIDED', name='journalentrystatus', schema='tenant'), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('entry_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index('ix_journal_entries_created_at', 'journal_entries', ['created_at'], unique=False, schema='tenant')
    _safe_create_index('ix_journal_entries_status', 'journal_entries', ['status'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_branch_id'), 'journal_entries', ['branch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_content_hash'), 'journal_entries', ['content_hash'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_reference'), 'journal_entries', ['reference'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_reference_id'), 'journal_entries', ['reference_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_reversal_of_id'), 'journal_entries', ['reversal_of_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_sequence_no'), 'journal_entries', ['sequence_no'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entries_submitted_by'), 'journal_entries', ['submitted_by'], unique=False, schema='tenant')
    _safe_create_table('price_list_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price_list_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_price_list_rules_item_id'), 'price_list_rules', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_price_list_rules_price_list_id'), 'price_list_rules', ['price_list_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_price_list_rules_variant_id'), 'price_list_rules', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('price_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_table('processed_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'consumer_name', 'event_id'),
    schema='tenant'
    )
    _safe_create_table('reconciliation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ERROR', name='reconciliationstatus', schema='tenant'), nullable=False),
    sa.Column('failed_checks', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_table('recurring_invoice_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurringfrequency', schema='tenant'), nullable=False),
    sa.Column('next_issue_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='recurringstatus', schema='tenant'), nullable=False),
    sa.Column('invoice_template_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_recurring_invoice_profiles_customer_id'), 'recurring_invoice_profiles', ['customer_id'], unique=False, schema='tenant')
    _safe_create_table('sales_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'INVOICED', 'CANCELLED', name='salesorderstatus', schema='tenant'), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_sales_orders_contact_id'), 'sales_orders', ['contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=True, schema='tenant')
    _safe_create_table('serial_numbers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('state', sa.Enum('IN_STOCK', 'RESERVED', 'SOLD', 'RETURNED', 'SCRAPPED', 'UNDER_REPAIR', name='serialstate'), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('current_owner_contact_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'serial_no', name='uq_serial_numbers_item_serial'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_serial_numbers_current_owner_contact_id'), 'serial_numbers', ['current_owner_contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_serial_numbers_item_id'), 'serial_numbers', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_serial_numbers_serial_no'), 'serial_numbers', ['serial_no'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_serial_numbers_variant_id'), 'serial_numbers', ['variant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_serial_numbers_warehouse_id'), 'serial_numbers', ['warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('stock_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_reserved', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_levels_non_negative'),
    sa.CheckConstraint('serial_id IS NULL OR quantity <= 1', name='ck_stock_levels_serial_qty_is_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'variant_id', 'warehouse_id', 'batch_id', 'serial_id', name='uq_stock_levels_granularity'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_levels_batch_id'), 'stock_levels', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_levels_item_id'), 'stock_levels', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_levels_serial_id'), 'stock_levels', ['serial_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_levels_warehouse_id'), 'stock_levels', ['warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('serial_id IS NULL OR qty = 1 OR qty = -1', name='ck_stock_movements_serial_qty_is_one'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_movements_contact_id'), 'stock_movements', ['contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_movements_occurred_at'), 'stock_movements', ['occurred_at'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_movements_serial_id'), 'stock_movements', ['serial_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('stock_reorder_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_reorder_rules_item_id'), 'stock_reorder_rules', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_reorder_rules_warehouse_id'), 'stock_reorder_rules', ['warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('stock_take_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_take_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('expected_qty', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('variance_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_take_lines_batch_id'), 'stock_take_lines', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_take_lines_item_id'), 'stock_take_lines', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_take_lines_serial_id'), 'stock_take_lines', ['serial_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_take_lines_stock_take_id'), 'stock_take_lines', ['stock_take_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_take_lines_variant_id'), 'stock_take_lines', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('stock_takes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COUNTING', 'REVIEW', 'POSTED', name='stocktakestatus'), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_takes_warehouse_id'), 'stock_takes', ['warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('stock_transfer_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty_dispatched', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('qty_dispatched > 0', name='ck_transfer_lines_qty_dispatched'),
    sa.CheckConstraint('qty_received >= 0', name='ck_transfer_lines_qty_received'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_transfer_lines_batch_id'), 'stock_transfer_lines', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfer_lines_item_id'), 'stock_transfer_lines', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfer_lines_serial_id'), 'stock_transfer_lines', ['serial_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfer_lines_transfer_id'), 'stock_transfer_lines', ['transfer_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfer_lines_variant_id'), 'stock_transfer_lines', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('stock_transfers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transfer_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('destination_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('transit_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_TRANSIT', 'COMPLETED', 'PARTIALLY_RECEIVED', name='transferstatus'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_warehouse_id != destination_warehouse_id AND source_warehouse_id != transit_warehouse_id AND destination_warehouse_id != transit_warehouse_id', name='ck_transfers_distinct_warehouses'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_stock_transfers_destination_warehouse_id'), 'stock_transfers', ['destination_warehouse_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfers_source_warehouse_id'), 'stock_transfers', ['source_warehouse_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfers_status'), 'stock_transfers', ['status'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfers_transfer_number'), 'stock_transfers', ['transfer_number'], unique=True, schema='tenant')
    _safe_create_index(op.f('ix_tenant_stock_transfers_transit_warehouse_id'), 'stock_transfers', ['transit_warehouse_id'], unique=False, schema='tenant')
    _safe_create_table('uoms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=18, scale=6), server_default=sa.text('1.0'), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_uoms_item_id'), 'uoms', ['item_id'], unique=False, schema='tenant')
    _safe_create_table('warehouses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sa.Enum('MAIN', 'RETAIL', 'TRANSIT', 'QUARANTINE', 'DAMAGED', 'CONSIGNMENT', name='warehousetype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_warehouses_code'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_warehouses_code'), 'warehouses', ['code'], unique=False, schema='tenant')
    _safe_create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['tenant.contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_invoices_number'),
    schema='tenant'
    )
    _safe_create_index('ix_invoices_status', 'invoices', ['status'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_invoices_contact_id'), 'invoices', ['contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False, schema='tenant')
    _safe_create_table('journal_entry_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('cost_center_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('(debit >= 0 AND credit >= 0) AND NOT (debit > 0 AND credit > 0) AND (debit > 0 OR credit > 0)', name='ck_journal_entry_lines_debit_xor_credit'),
    sa.ForeignKeyConstraint(['account_id'], ['tenant.accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['tenant.journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_journal_entry_lines_account_code'), 'journal_entry_lines', ['account_code'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entry_lines_account_id'), 'journal_entry_lines', ['account_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entry_lines_branch_id'), 'journal_entry_lines', ['branch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entry_lines_contact_id'), 'journal_entry_lines', ['contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entry_lines_cost_center_id'), 'journal_entry_lines', ['cost_center_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False, schema='tenant')
    _safe_create_table('sales_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED', 'WITHDRAWN', 'REVERSED', 'CLOSED', name='documentstate', schema='tenant'), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_of_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'PAID', 'CANCELLED', name='salesinvoicestatus', schema='tenant'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tenant.sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_sales_invoices_contact_id'), 'sales_invoices', ['contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoices_content_hash'), 'sales_invoices', ['content_hash'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoices_invoice_number'), 'sales_invoices', ['invoice_number'], unique=True, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoices_order_id'), 'sales_invoices', ['order_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoices_reversal_of_id'), 'sales_invoices', ['reversal_of_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoices_submitted_by'), 'sales_invoices', ['submitted_by'], unique=False, schema='tenant')
    _safe_create_table('sales_order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fulfilled_qty', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('fulfilled_qty >= 0', name='ck_sales_order_lines_fulfilled_qty_non_negative'),
    sa.CheckConstraint('qty > 0', name='ck_sales_order_lines_qty_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_order_lines_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['tenant.sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_sales_order_lines_item_id'), 'sales_order_lines', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_order_lines_order_id'), 'sales_order_lines', ['order_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_order_lines_uom_id'), 'sales_order_lines', ['uom_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_order_lines_variant_id'), 'sales_order_lines', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_lines_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_lines_price'),
    sa.ForeignKeyConstraint(['invoice_id'], ['tenant.invoices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['tenant.items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_invoice_lines_item_id'), 'invoice_lines', ['item_id'], unique=False, schema='tenant')
    _safe_create_table('sales_invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=18, scale=4), server_default=sa.text('0.1400'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_sales_invoice_lines_qty_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_sales_invoice_lines_tax_amount_non_negative'),
    sa.CheckConstraint('tax_rate >= 0', name='ck_sales_invoice_lines_tax_rate_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_invoice_lines_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['tenant.sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_sales_invoice_lines_invoice_id'), 'sales_invoice_lines', ['invoice_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoice_lines_item_id'), 'sales_invoice_lines', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoice_lines_uom_id'), 'sales_invoice_lines', ['uom_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_invoice_lines_variant_id'), 'sales_invoice_lines', ['variant_id'], unique=False, schema='tenant')
    _safe_create_table('sales_returns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED', 'WITHDRAWN', 'REVERSED', 'CLOSED', name='documentstate', schema='tenant'), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_of_id', sa.Uuid(), nullable=True),
    sa.Column('return_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RECEIVED', 'CREDITED', name='salesreturnstatus', schema='tenant'), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['tenant.sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['tenant.sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['tenant.sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_sales_returns_contact_id'), 'sales_returns', ['contact_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_content_hash'), 'sales_returns', ['content_hash'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_credit_note_id'), 'sales_returns', ['credit_note_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_invoice_id'), 'sales_returns', ['invoice_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_order_id'), 'sales_returns', ['order_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_return_number'), 'sales_returns', ['return_number'], unique=True, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_reversal_of_id'), 'sales_returns', ['reversal_of_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_returns_submitted_by'), 'sales_returns', ['submitted_by'], unique=False, schema='tenant')
    _safe_create_table('sales_return_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_id', sa.Uuid(), nullable=False),
    sa.Column('original_invoice_line_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=18, scale=4), server_default=sa.text('0.1400'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_sales_return_lines_qty_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_sales_return_lines_tax_amount_non_negative'),
    sa.CheckConstraint('tax_rate >= 0', name='ck_sales_return_lines_tax_rate_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_return_lines_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['original_invoice_line_id'], ['tenant.sales_invoice_lines.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['tenant.sales_returns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    _safe_create_index(op.f('ix_tenant_sales_return_lines_batch_id'), 'sales_return_lines', ['batch_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_return_lines_item_id'), 'sales_return_lines', ['item_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_return_lines_original_invoice_line_id'), 'sales_return_lines', ['original_invoice_line_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_return_lines_return_id'), 'sales_return_lines', ['return_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_return_lines_serial_id'), 'sales_return_lines', ['serial_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_return_lines_uom_id'), 'sales_return_lines', ['uom_id'], unique=False, schema='tenant')
    _safe_create_index(op.f('ix_tenant_sales_return_lines_variant_id'), 'sales_return_lines', ['variant_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_sales_return_lines_variant_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_return_lines_uom_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_return_lines_serial_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_return_lines_return_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_return_lines_original_invoice_line_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_return_lines_item_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_return_lines_batch_id'), table_name='sales_return_lines', schema='tenant')
    op.drop_table('sales_return_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_submitted_by'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_reversal_of_id'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_return_number'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_order_id'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_invoice_id'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_credit_note_id'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_content_hash'), table_name='sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_returns_contact_id'), table_name='sales_returns', schema='tenant')
    op.drop_table('sales_returns', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoice_lines_variant_id'), table_name='sales_invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoice_lines_uom_id'), table_name='sales_invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoice_lines_item_id'), table_name='sales_invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoice_lines_invoice_id'), table_name='sales_invoice_lines', schema='tenant')
    op.drop_table('sales_invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoice_lines_item_id'), table_name='invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoice_lines_invoice_id'), table_name='invoice_lines', schema='tenant')
    op.drop_table('invoice_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_order_lines_variant_id'), table_name='sales_order_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_order_lines_uom_id'), table_name='sales_order_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_order_lines_order_id'), table_name='sales_order_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_order_lines_item_id'), table_name='sales_order_lines', schema='tenant')
    op.drop_table('sales_order_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoices_submitted_by'), table_name='sales_invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoices_reversal_of_id'), table_name='sales_invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoices_order_id'), table_name='sales_invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoices_invoice_number'), table_name='sales_invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoices_content_hash'), table_name='sales_invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_invoices_contact_id'), table_name='sales_invoices', schema='tenant')
    op.drop_table('sales_invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entry_lines_cost_center_id'), table_name='journal_entry_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entry_lines_contact_id'), table_name='journal_entry_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entry_lines_branch_id'), table_name='journal_entry_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entry_lines_account_id'), table_name='journal_entry_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entry_lines_account_code'), table_name='journal_entry_lines', schema='tenant')
    op.drop_table('journal_entry_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoices_invoice_number'), table_name='invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_invoices_contact_id'), table_name='invoices', schema='tenant')
    op.drop_index('ix_invoices_status', table_name='invoices', schema='tenant')
    op.drop_table('invoices', schema='tenant')
    op.drop_index(op.f('ix_tenant_warehouses_code'), table_name='warehouses', schema='tenant')
    op.drop_table('warehouses', schema='tenant')
    op.drop_index(op.f('ix_tenant_uoms_item_id'), table_name='uoms', schema='tenant')
    op.drop_table('uoms', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_transit_warehouse_id'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_transfer_number'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_status'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_source_warehouse_id'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_destination_warehouse_id'), table_name='stock_transfers', schema='tenant')
    op.drop_table('stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_variant_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_transfer_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_serial_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_item_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_batch_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_table('stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_takes_warehouse_id'), table_name='stock_takes', schema='tenant')
    op.drop_table('stock_takes', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_variant_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_stock_take_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_serial_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_item_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_batch_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_table('stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_reorder_rules_warehouse_id'), table_name='stock_reorder_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_reorder_rules_item_id'), table_name='stock_reorder_rules', schema='tenant')
    op.drop_table('stock_reorder_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_warehouse_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_variant_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_serial_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_occurred_at'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_item_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_contact_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_batch_id'), table_name='stock_movements', schema='tenant')
    op.drop_table('stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_warehouse_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_variant_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_serial_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_item_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_batch_id'), table_name='stock_levels', schema='tenant')
    op.drop_table('stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_warehouse_id'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_variant_id'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_serial_no'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_item_id'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_current_owner_contact_id'), table_name='serial_numbers', schema='tenant')
    op.drop_table('serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_orders_order_number'), table_name='sales_orders', schema='tenant')
    op.drop_index(op.f('ix_tenant_sales_orders_contact_id'), table_name='sales_orders', schema='tenant')
    op.drop_table('sales_orders', schema='tenant')
    op.drop_index(op.f('ix_tenant_recurring_invoice_profiles_customer_id'), table_name='recurring_invoice_profiles', schema='tenant')
    op.drop_table('recurring_invoice_profiles', schema='tenant')
    op.drop_table('reconciliation_runs', schema='tenant')
    op.drop_table('processed_events', schema='tenant')
    op.drop_table('price_lists', schema='tenant')
    op.drop_index(op.f('ix_tenant_price_list_rules_variant_id'), table_name='price_list_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_price_list_rules_price_list_id'), table_name='price_list_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_price_list_rules_item_id'), table_name='price_list_rules', schema='tenant')
    op.drop_table('price_list_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_submitted_by'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_sequence_no'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_reversal_of_id'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_reference_id'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_reference'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_content_hash'), table_name='journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_journal_entries_branch_id'), table_name='journal_entries', schema='tenant')
    op.drop_index('ix_journal_entries_status', table_name='journal_entries', schema='tenant')
    op.drop_index('ix_journal_entries_created_at', table_name='journal_entries', schema='tenant')
    op.drop_table('journal_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_items_sku'), table_name='items', schema='tenant')
    op.drop_index(op.f('ix_tenant_items_egs_code'), table_name='items', schema='tenant')
    op.drop_table('items', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_variants_sku'), table_name='item_variants', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_variants_item_id'), table_name='item_variants', schema='tenant')
    op.drop_table('item_variants', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_variant_id'), table_name='item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_uom_id'), table_name='item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_item_id'), table_name='item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_barcode'), table_name='item_barcodes', schema='tenant')
    op.drop_table('item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_tenant_configs_tenant_id'), table_name='eta_tenant_configs', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_tenant_configs_taxpayer_rin'), table_name='eta_tenant_configs', schema='tenant')
    op.drop_table('eta_tenant_configs', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_submissions_tenant_id'), table_name='eta_submissions', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_submissions_submission_uuid'), table_name='eta_submissions', schema='tenant')
    op.drop_table('eta_submissions', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipts_uuid'), table_name='eta_receipts', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipts_tenant_id'), table_name='eta_receipts', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipts_state'), table_name='eta_receipts', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipts_receipt_number'), table_name='eta_receipts', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipts_internal_doc_id'), table_name='eta_receipts', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipts_batch_id'), table_name='eta_receipts', schema='tenant')
    op.drop_table('eta_receipts', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipt_batches_tenant_id'), table_name='eta_receipt_batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipt_batches_submission_uuid'), table_name='eta_receipt_batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipt_batches_state'), table_name='eta_receipt_batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_receipt_batches_pos_terminal_id'), table_name='eta_receipt_batches', schema='tenant')
    op.drop_table('eta_receipt_batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_uuid'), table_name='eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_tenant_id'), table_name='eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_submission_uuid'), table_name='eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_state'), table_name='eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_internal_doc_type'), table_name='eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_internal_doc_id'), table_name='eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_eta_documents_eta_document_type'), table_name='eta_documents', schema='tenant')
    op.drop_table('eta_documents', schema='tenant')
    op.drop_index(op.f('ix_tenant_egs_codes_variant_id'), table_name='egs_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_egs_codes_tenant_id'), table_name='egs_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_egs_codes_item_id'), table_name='egs_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_egs_codes_is_active'), table_name='egs_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_egs_codes_code_value'), table_name='egs_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_egs_codes_code_type'), table_name='egs_codes', schema='tenant')
    op.drop_table('egs_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_document_sequences_document_type'), table_name='document_sequences', schema='tenant')
    op.drop_index(op.f('ix_tenant_document_sequences_branch_id'), table_name='document_sequences', schema='tenant')
    op.drop_table('document_sequences', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_warehouse_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_variant_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_serial_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_item_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_batch_id'), table_name='cost_layers', schema='tenant')
    op.drop_table('cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_consumptions_movement_id'), table_name='cost_consumptions', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_consumptions_layer_id'), table_name='cost_consumptions', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_consumptions_adjustment_of_id'), table_name='cost_consumptions', schema='tenant')
    op.drop_table('cost_consumptions', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_phone_e164'), table_name='contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_phone'), table_name='contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_name'), table_name='contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_contacts_branch_id'), table_name='contacts', schema='tenant')
    op.drop_index('ix_contacts_type', table_name='contacts', schema='tenant')
    op.drop_index('ix_contacts_status', table_name='contacts', schema='tenant')
    op.drop_table('contacts', schema='tenant')
    op.drop_index(op.f('ix_tenant_branches_name'), table_name='branches', schema='tenant')
    op.drop_index(op.f('ix_tenant_branches_code'), table_name='branches', schema='tenant')
    op.drop_table('branches', schema='tenant')
    op.drop_index(op.f('ix_tenant_batches_variant_id'), table_name='batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_batches_item_id'), table_name='batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_batches_batch_no'), table_name='batches', schema='tenant')
    op.drop_table('batches', schema='tenant')
    op.drop_index('ix_audit_logs_occurred_at', table_name='audit_logs', schema='tenant')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs', schema='tenant')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs', schema='tenant')
    op.drop_table('audit_logs', schema='tenant')
    op.drop_table('attachments', schema='tenant')
    op.drop_index(op.f('ix_tenant_accounts_code'), table_name='accounts', schema='tenant')
    op.drop_index('ix_accounts_type', table_name='accounts', schema='tenant')
    op.drop_table('accounts', schema='tenant')
    op.drop_table('accounting_periods', schema='tenant')
    # ### end Alembic commands ###
