"""Phase 1b Step 6 Complete Inventory

Revision ID: f93809b48226
Revises: 9b84e0dfc847
Create Date: 2026-07-26 23:19:33.864442+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f93809b48226'
down_revision: Union[str, None] = '9b84e0dfc847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: audit_logs already created by f3a8c91d4e72_add_sequences_audit_hash
    # NOTE: document_sequences already created by f3a8c91d4e72_add_sequences_audit_hash
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('batch_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'QUARANTINED', 'RECALLED', name='batchstatus', schema='tenant'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'batch_no', name='uq_batches_item_batch'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_batches_batch_no'), 'batches', ['batch_no'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_batches_item_id'), 'batches', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_batches_variant_id'), 'batches', ['variant_id'], unique=False, schema='tenant')
    op.create_table('cost_consumptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('layer_id', sa.Uuid(), nullable=False),
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('qty_consumed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_at_consumption', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjustment_of_id', sa.Uuid(), nullable=True),
    sa.Column('adjustment_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_cost_consumptions_adjustment_of_id'), 'cost_consumptions', ['adjustment_of_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_cost_consumptions_layer_id'), 'cost_consumptions', ['layer_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_cost_consumptions_movement_id'), 'cost_consumptions', ['movement_id'], unique=False, schema='tenant')
    op.create_table('cost_layers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_original', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_current', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('landed_cost_applied', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty_received >= 0', name='ck_cost_layers_received'),
    sa.CheckConstraint('qty_remaining >= 0', name='ck_cost_layers_remaining'),
    sa.CheckConstraint('serial_id IS NULL OR qty_received = 1', name='ck_cost_layers_serial_layer_qty_is_one'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_cost_layers_batch_id'), 'cost_layers', ['batch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_cost_layers_item_id'), 'cost_layers', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_cost_layers_serial_id'), 'cost_layers', ['serial_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_cost_layers_variant_id'), 'cost_layers', ['variant_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_cost_layers_warehouse_id'), 'cost_layers', ['warehouse_id'], unique=False, schema='tenant')
    op.create_table('item_barcodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name='uq_item_barcodes_barcode'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_item_barcodes_barcode'), 'item_barcodes', ['barcode'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_item_barcodes_item_id'), 'item_barcodes', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_item_barcodes_uom_id'), 'item_barcodes', ['uom_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_item_barcodes_variant_id'), 'item_barcodes', ['variant_id'], unique=False, schema='tenant')
    op.create_table('item_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('requires_batch', sa.Boolean(), nullable=False),
    sa.Column('requires_serial', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_item_variants_sku'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_item_variants_item_id'), 'item_variants', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_item_variants_sku'), 'item_variants', ['sku'], unique=False, schema='tenant')
    # NOTE: `items` was already created by 226439fee167_init_tenant (with
    # id/sku/name/name_ar/description/category/price/cost/quantity_on_hand/
    # reorder_level/is_active/created_by/created_at). This migration
    # originally re-issued a full duplicate create_table('items', ...),
    # which crashes with "relation already exists" on a real Postgres
    # database. Only egs_code/costing_method/requires_batch/requires_serial
    # are genuinely new here (added by the current Item model), so they are
    # now added via op.add_column instead of being duplicated.
    op.add_column('items', sa.Column('egs_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True), schema='tenant')
    op.add_column('items', sa.Column('costing_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True), schema='tenant')
    op.add_column('items', sa.Column('requires_batch', sa.Boolean(), nullable=False, server_default=sa.text('false')), schema='tenant')
    op.add_column('items', sa.Column('requires_serial', sa.Boolean(), nullable=False, server_default=sa.text('false')), schema='tenant')
    op.create_index(op.f('ix_tenant_items_egs_code'), 'items', ['egs_code'], unique=False, schema='tenant')
    op.create_table('price_list_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price_list_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_price_list_rules_item_id'), 'price_list_rules', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_price_list_rules_price_list_id'), 'price_list_rules', ['price_list_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_price_list_rules_variant_id'), 'price_list_rules', ['variant_id'], unique=False, schema='tenant')
    op.create_table('price_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_table('serial_numbers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('state', sa.Enum('IN_STOCK', 'RESERVED', 'SOLD', 'RETURNED', 'SCRAPPED', 'UNDER_REPAIR', name='serialstate', schema='tenant'), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('current_owner_contact_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'serial_no', name='uq_serial_numbers_item_serial'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_serial_numbers_current_owner_contact_id'), 'serial_numbers', ['current_owner_contact_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_serial_numbers_item_id'), 'serial_numbers', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_serial_numbers_serial_no'), 'serial_numbers', ['serial_no'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_serial_numbers_variant_id'), 'serial_numbers', ['variant_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_serial_numbers_warehouse_id'), 'serial_numbers', ['warehouse_id'], unique=False, schema='tenant')
    op.create_table('stock_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_reserved', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_levels_non_negative'),
    sa.CheckConstraint('serial_id IS NULL OR quantity <= 1', name='ck_stock_levels_serial_qty_is_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'variant_id', 'warehouse_id', 'batch_id', 'serial_id', name='uq_stock_levels_granularity'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_levels_batch_id'), 'stock_levels', ['batch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_levels_item_id'), 'stock_levels', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_levels_serial_id'), 'stock_levels', ['serial_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_levels_warehouse_id'), 'stock_levels', ['warehouse_id'], unique=False, schema='tenant')
    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('serial_id IS NULL OR qty = 1 OR qty = -1', name='ck_stock_movements_serial_qty_is_one'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_movements_contact_id'), 'stock_movements', ['contact_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_movements_occurred_at'), 'stock_movements', ['occurred_at'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_movements_serial_id'), 'stock_movements', ['serial_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False, schema='tenant')
    op.create_table('stock_reorder_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_reorder_rules_item_id'), 'stock_reorder_rules', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_reorder_rules_warehouse_id'), 'stock_reorder_rules', ['warehouse_id'], unique=False, schema='tenant')
    op.create_table('stock_take_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_take_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('expected_qty', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('variance_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_take_lines_batch_id'), 'stock_take_lines', ['batch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_take_lines_item_id'), 'stock_take_lines', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_take_lines_serial_id'), 'stock_take_lines', ['serial_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_take_lines_stock_take_id'), 'stock_take_lines', ['stock_take_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_take_lines_variant_id'), 'stock_take_lines', ['variant_id'], unique=False, schema='tenant')
    op.create_table('stock_takes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COUNTING', 'REVIEW', 'POSTED', name='stocktakestatus', schema='tenant'), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_takes_warehouse_id'), 'stock_takes', ['warehouse_id'], unique=False, schema='tenant')
    op.create_table('stock_transfer_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('serial_id', sa.Uuid(), nullable=True),
    sa.Column('qty_dispatched', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('qty_dispatched > 0', name='ck_transfer_lines_qty_dispatched'),
    sa.CheckConstraint('qty_received >= 0', name='ck_transfer_lines_qty_received'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_transfer_lines_batch_id'), 'stock_transfer_lines', ['batch_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfer_lines_item_id'), 'stock_transfer_lines', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfer_lines_serial_id'), 'stock_transfer_lines', ['serial_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfer_lines_transfer_id'), 'stock_transfer_lines', ['transfer_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfer_lines_variant_id'), 'stock_transfer_lines', ['variant_id'], unique=False, schema='tenant')
    op.create_table('stock_transfers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transfer_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('destination_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('transit_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_TRANSIT', 'COMPLETED', 'PARTIALLY_RECEIVED', name='transferstatus', schema='tenant'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_warehouse_id != destination_warehouse_id AND source_warehouse_id != transit_warehouse_id AND destination_warehouse_id != transit_warehouse_id', name='ck_transfers_distinct_warehouses'),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_stock_transfers_destination_warehouse_id'), 'stock_transfers', ['destination_warehouse_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfers_source_warehouse_id'), 'stock_transfers', ['source_warehouse_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfers_status'), 'stock_transfers', ['status'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfers_transfer_number'), 'stock_transfers', ['transfer_number'], unique=True, schema='tenant')
    op.create_index(op.f('ix_tenant_stock_transfers_transit_warehouse_id'), 'stock_transfers', ['transit_warehouse_id'], unique=False, schema='tenant')
    op.create_table('uoms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=18, scale=6), server_default=sa.text('1.0'), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_uoms_item_id'), 'uoms', ['item_id'], unique=False, schema='tenant')
    op.create_table('warehouses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sa.Enum('MAIN', 'RETAIL', 'TRANSIT', 'QUARANTINE', 'DAMAGED', 'CONSIGNMENT', name='warehousetype', schema='tenant'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_warehouses_code'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_warehouses_code'), 'warehouses', ['code'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_warehouses_code'), table_name='warehouses', schema='tenant')
    op.drop_table('warehouses', schema='tenant')
    op.drop_index(op.f('ix_tenant_uoms_item_id'), table_name='uoms', schema='tenant')
    op.drop_table('uoms', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_transit_warehouse_id'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_transfer_number'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_status'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_source_warehouse_id'), table_name='stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfers_destination_warehouse_id'), table_name='stock_transfers', schema='tenant')
    op.drop_table('stock_transfers', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_variant_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_transfer_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_serial_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_item_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_transfer_lines_batch_id'), table_name='stock_transfer_lines', schema='tenant')
    op.drop_table('stock_transfer_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_takes_warehouse_id'), table_name='stock_takes', schema='tenant')
    op.drop_table('stock_takes', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_variant_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_stock_take_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_serial_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_item_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_take_lines_batch_id'), table_name='stock_take_lines', schema='tenant')
    op.drop_table('stock_take_lines', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_reorder_rules_warehouse_id'), table_name='stock_reorder_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_reorder_rules_item_id'), table_name='stock_reorder_rules', schema='tenant')
    op.drop_table('stock_reorder_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_warehouse_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_variant_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_serial_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_occurred_at'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_item_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_contact_id'), table_name='stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_movements_batch_id'), table_name='stock_movements', schema='tenant')
    op.drop_table('stock_movements', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_warehouse_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_variant_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_serial_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_item_id'), table_name='stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_stock_levels_batch_id'), table_name='stock_levels', schema='tenant')
    op.drop_table('stock_levels', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_warehouse_id'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_variant_id'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_serial_no'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_item_id'), table_name='serial_numbers', schema='tenant')
    op.drop_index(op.f('ix_tenant_serial_numbers_current_owner_contact_id'), table_name='serial_numbers', schema='tenant')
    op.drop_table('serial_numbers', schema='tenant')
    op.drop_table('price_lists', schema='tenant')
    op.drop_index(op.f('ix_tenant_price_list_rules_variant_id'), table_name='price_list_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_price_list_rules_price_list_id'), table_name='price_list_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_price_list_rules_item_id'), table_name='price_list_rules', schema='tenant')
    op.drop_table('price_list_rules', schema='tenant')
    op.drop_index(op.f('ix_tenant_items_egs_code'), table_name='items', schema='tenant')
    op.drop_column('items', 'requires_serial', schema='tenant')
    op.drop_column('items', 'requires_batch', schema='tenant')
    op.drop_column('items', 'costing_method', schema='tenant')
    op.drop_column('items', 'egs_code', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_variants_sku'), table_name='item_variants', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_variants_item_id'), table_name='item_variants', schema='tenant')
    op.drop_table('item_variants', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_variant_id'), table_name='item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_uom_id'), table_name='item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_item_id'), table_name='item_barcodes', schema='tenant')
    op.drop_index(op.f('ix_tenant_item_barcodes_barcode'), table_name='item_barcodes', schema='tenant')
    op.drop_table('item_barcodes', schema='tenant')
    # NOTE: document_sequences dropped by f3a8c91d4e72_add_sequences_audit_hash downgrade
    op.drop_index(op.f('ix_tenant_cost_layers_warehouse_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_variant_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_serial_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_item_id'), table_name='cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_layers_batch_id'), table_name='cost_layers', schema='tenant')
    op.drop_table('cost_layers', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_consumptions_movement_id'), table_name='cost_consumptions', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_consumptions_layer_id'), table_name='cost_consumptions', schema='tenant')
    op.drop_index(op.f('ix_tenant_cost_consumptions_adjustment_of_id'), table_name='cost_consumptions', schema='tenant')
    op.drop_table('cost_consumptions', schema='tenant')
    op.drop_index(op.f('ix_tenant_batches_variant_id'), table_name='batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_batches_item_id'), table_name='batches', schema='tenant')
    op.drop_index(op.f('ix_tenant_batches_batch_no'), table_name='batches', schema='tenant')
    op.drop_table('batches', schema='tenant')
    # NOTE: audit_logs dropped by f3a8c91d4e72_add_sequences_audit_hash downgrade
    # ### end Alembic commands ###
